wallpaper {
    monitor = DP-1
    path = /home/razor/Wallpapers/5120/5120x1440wallpaper_51202139522_o.png
}
wallpaper {
    monitor = HDMI-A-1
    path = /home/razor/Wallpapers/1920/wp4002579.jpg
}


