###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

monitor=DP-1, 5120x1440@239.76, 0x0, 1
monitor=HDMI-A-1, 1920x1080@100.00, 5120x-240, 1, transform, 1
